// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqH6xC-XP8nJEi7Qnu1EbTd5ZfZUFWPk8',
    appId: '1:251632185451:web:901e841de52e1bba7f012e',
    messagingSenderId: '251632185451',
    projectId: 'emerge-fa3ce',
    authDomain: 'emerge-fa3ce.firebaseapp.com',
    storageBucket: 'emerge-fa3ce.firebasestorage.app',
    measurementId: 'G-DPPZH1C731',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_es27K21CeVZ639sbL41RIxZUrpK8JnU',
    appId: '1:251632185451:android:10e8dd50ee32ad5e7f012e',
    messagingSenderId: '251632185451',
    projectId: 'emerge-fa3ce',
    storageBucket: 'emerge-fa3ce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4HCkbbJk_wBKSsEMFV4VJdXf1W6p6gQg',
    appId: '1:251632185451:ios:405d844693b970f87f012e',
    messagingSenderId: '251632185451',
    projectId: 'emerge-fa3ce',
    storageBucket: 'emerge-fa3ce.firebasestorage.app',
    iosBundleId: 'com.example.emergeHomely',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4HCkbbJk_wBKSsEMFV4VJdXf1W6p6gQg',
    appId: '1:251632185451:ios:405d844693b970f87f012e',
    messagingSenderId: '251632185451',
    projectId: 'emerge-fa3ce',
    storageBucket: 'emerge-fa3ce.firebasestorage.app',
    iosBundleId: 'com.example.emergeHomely',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqH6xC-XP8nJEi7Qnu1EbTd5ZfZUFWPk8',
    appId: '1:251632185451:web:c4c3804e2a9529d77f012e',
    messagingSenderId: '251632185451',
    projectId: 'emerge-fa3ce',
    authDomain: 'emerge-fa3ce.firebaseapp.com',
    storageBucket: 'emerge-fa3ce.firebasestorage.app',
    measurementId: 'G-SGXDYM9T07',
  );
}
